### ISSUE TITLE
wrong conversion result

### ISSUE THREAD

**Issue by mzdhr** [msarhan/ummalqura-calendar#13]
I'm getting wrong result when I try to conversion dates! amost 1 month dely!

**Comment by msarhan** [comment]
Please provide an example

**Comment by A7medArafah** [comment]
I have same problem today 
Example : 
` Calendar uCal = new UmmalquraCalendar(1439, UmmalquraCalendar.RAJAB, 15);
 GregorianCalendar gCal = new GregorianCalendar();
 gCal.setTime(uCal.getTime());

		gCal.get(Calendar.YEAR);         // 2012
		gCal.get(Calendar.MONTH);        // 1
		gCal.get(Calendar.DAY_OF_MONTH); // 7
		
		System.out.println(gCal.getTime());`

Same result if i choose JUMADA_THANI
Calendar uCal = new UmmalquraCalendar(1439, UmmalquraCalendar.JUMADA_THANI, 15);


Please Fix it ASAP.
