### ISSUE TITLE
Issues Date Conversion

### ISSUE THREAD

**Issue by A7medArafah** [msarhan/ummalqura-calendar#16]
I have same problem today
Example :
` Calendar uCal = new UmmalquraCalendar(1439, UmmalquraCalendar.RAJAB, 15);
GregorianCalendar gCal = new GregorianCalendar();
gCal.setTime(uCal.getTime());

gCal.get(Calendar.YEAR);         
gCal.get(Calendar.MONTH);        
gCal.get(Calendar.DAY_OF_MONTH); 
	
System.out.println(gCal.getTime());`
Same result if i choose JUMADA_THANI
Calendar uCal = new UmmalquraCalendar(1439, UmmalquraCalendar.JUMADA_THANI, 15);

Please Fix it ASAP.

**Comment by MenoData** [comment]
I have executed this example and found the library to be correct. The example returns the gregorian date 2018-04-01 (for AH-1439-RAJAB-15). This is in agreement with what the [official website](http://www.ummulqura.org.sa/Index.aspx) of Saudi Arabia says. So I suggest to close this confusing issue.
