### ISSUE TITLE
Adding an offset

### ISSUE THREAD

**Issue by msadrud** [msarhan/ummalqura-calendar#18]
Hi,
Thanks for the wonderful work. 
I wanted to check if there is any mechanism to (+) or (-) offset days to this calendar? As the calculation of this algorithm may differ by a day or two depending on moon sighting. Please let me know. Thank you.

regards,
Mohammed

**Comment by msarhan** [comment]
@msadrud Thanks and sorry for the late response.
Actually, this library uses astronomical data to compute the length of each month. So it is algorithmically calculation and cannot be adjusted.
Sorry :(
