### ISSUE TITLE
Formatting not work in samsung android devices. 

### ISSUE THREAD

**Issue by ibadurrahmantalha** [msarhan/ummalqura-calendar#20]
i try it on other devices and it work perfect. But on Samsung devices it not working. below format i have checked on many devices:
dateFormat.applyPattern("d MMMM, y");
in Samsung device it give "05 0009, 1441", while on other it give "05 Ramadhan, 1441"

**Comment by Al-Hussein-96** [comment]
@ibadurrahmantalha  any soultion ?

**Comment by joeyoggie** [comment]
@ibadurrahmantalha I'm having something similar to this. My required pattern is "yyyy-MM-dd".
On Samsung devices, it outputs: 1423-Rab-I-10 (notice the wrong month, but should be 02 not Rab-I)
On OnePlus/Emulator, it outputs: 1423-02-10 which is correct.

**Comment by hussein16hamada** [comment]
I have the same issue

**Comment by msarhan** [comment]
I've added a test case for this issue: https://github.com/msarhan/ummalqura-calendar/blob/9c7b336b5062742bdb894f0c6ce31e065e08ed2e/src/test/java/com/github/msarhan/ummalqura/calendar/UmmalquraDateFormatTest.java#L113-L121
It is working fine using `dd MMMM, y` format.
