### ISSUE TITLE
Example of Hijri Calendar in Gridview

### ISSUE THREAD

**Issue by wdnk** [msarhan/ummalqura-calendar#5]
Hi, i want to make a calendar app. that show 1st day to the last of hijri month with GridView (columns : 7), would you like to help me, please?

**Comment by iturki** [comment]
This is a new lib that might be helpful to you:
https://github.com/alhzmy13/HijriDatePicker

**Comment by msarhan** [comment]
@wdnk I've added new 'lengthOfMonth' and 'lengthOfYear' functions. Hope will help you in your App!
